import { HistoricalRecord } from "./types";

export const HISTORICAL_DATA: HistoricalRecord[] = [
  {
    driver_age: 22,
    vehicle_age: 3,
    vehicle_type: "Sedan",
    previous_claims: 0,
    annual_mileage: 12000,
    estimated_repair_cost: 12000,
    claim_type: "Minor",
    risk_score: 40,
    risk_category: "Medium Risk",
    calculated_premium: 6000,
    claim_reserve: 15000,
  },
  {
    driver_age: 45,
    vehicle_age: 2,
    vehicle_type: "SUV",
    previous_claims: 1,
    annual_mileage: 15000,
    estimated_repair_cost: 32000,
    claim_type: "Moderate",
    risk_score: 20,
    risk_category: "Low Risk",
    calculated_premium: 5750,
    claim_reserve: 40000,
  },
  {
    driver_age: 65,
    vehicle_age: 8,
    vehicle_type: "Luxury",
    previous_claims: 3,
    annual_mileage: 18000,
    estimated_repair_cost: 85000,
    claim_type: "Major",
    risk_score: 70,
    risk_category: "High Risk",
    calculated_premium: 8250,
    claim_reserve: 85000,
  },
  {
    driver_age: 31,
    vehicle_age: 6,
    vehicle_type: "Hatchback",
    previous_claims: 0,
    annual_mileage: 8000,
    estimated_repair_cost: 8000,
    claim_type: "Minor",
    risk_score: 20,
    risk_category: "Low Risk",
    calculated_premium: 5500,
    claim_reserve: 15000,
  },
  {
    driver_age: 19,
    vehicle_age: 1,
    vehicle_type: "Sedan",
    previous_claims: 2,
    annual_mileage: 22000,
    estimated_repair_cost: 45000,
    claim_type: "Moderate",
    risk_score: 80,
    risk_category: "High Risk",
    calculated_premium: 8000,
    claim_reserve: 45000,
  },
  {
    driver_age: 52,
    vehicle_age: 10,
    vehicle_type: "SUV",
    previous_claims: 0,
    annual_mileage: 14000,
    estimated_repair_cost: 5000,
    claim_type: "Minor",
    risk_score: 25,
    risk_category: "Low Risk",
    calculated_premium: 5500,
    claim_reserve: 15000,
  },
  {
    driver_age: 28,
    vehicle_age: 4,
    vehicle_type: "Luxury",
    previous_claims: 1,
    annual_mileage: 24000,
    estimated_repair_cost: 120000,
    claim_type: "Major",
    risk_score: 35,
    risk_category: "Medium Risk",
    calculated_premium: 6750,
    claim_reserve: 120000,
  },
  {
    driver_age: 38,
    vehicle_age: 7,
    vehicle_type: "Sedan",
    previous_claims: 0,
    annual_mileage: 11000,
    estimated_repair_cost: 0,
    claim_type: "Minor",
    risk_score: 20,
    risk_category: "Low Risk",
    calculated_premium: 5500,
    claim_reserve: 0,
  },
  {
    driver_age: 58,
    vehicle_age: 5,
    vehicle_type: "Hatchback",
    previous_claims: 1,
    annual_mileage: 19500,
    estimated_repair_cost: 18000,
    claim_type: "Minor",
    risk_score: 20,
    risk_category: "Low Risk",
    calculated_premium: 5750,
    claim_reserve: 18000,
  },
  {
    driver_age: 24,
    vehicle_age: 6,
    vehicle_type: "SUV",
    previous_claims: 2,
    annual_mileage: 25000,
    estimated_repair_cost: 62000,
    claim_type: "Moderate",
    risk_score: 65,
    risk_category: "High Risk",
    calculated_premium: 8500,
    claim_reserve: 62000,
  },
  {
    driver_age: 41,
    vehicle_age: 3,
    vehicle_type: "Sedan",
    previous_claims: 4,
    annual_mileage: 9000,
    estimated_repair_cost: 35000,
    claim_type: "Moderate",
    risk_score: 45,
    risk_category: "Medium Risk",
    calculated_premium: 6250,
    claim_reserve: 40000,
  },
  {
    driver_age: 72,
    vehicle_age: 12,
    vehicle_type: "Hatchback",
    previous_claims: 0,
    annual_mileage: 5000,
    estimated_repair_cost: 3000,
    claim_type: "Minor",
    risk_score: 35,
    risk_category: "Medium Risk",
    calculated_premium: 5500,
    claim_reserve: 15000,
  },
  {
    driver_age: 35,
    vehicle_age: 2,
    vehicle_type: "Luxury",
    previous_claims: 0,
    annual_mileage: 14500,
    estimated_repair_cost: 95000,
    claim_type: "Major",
    risk_score: 15,
    risk_category: "Low Risk",
    calculated_premium: 6000,
    claim_reserve: 95000,
  },
  {
    driver_age: 21,
    vehicle_age: 8,
    vehicle_type: "SUV",
    previous_claims: 1,
    annual_mileage: 28000,
    estimated_repair_cost: 28000,
    claim_type: "Moderate",
    risk_score: 65,
    risk_category: "High Risk",
    calculated_premium: 8500,
    claim_reserve: 40000,
  },
  {
    driver_age: 50,
    vehicle_age: 4,
    vehicle_type: "Sedan",
    previous_claims: 2,
    annual_mileage: 16000,
    estimated_repair_cost: 15000,
    claim_type: "Minor",
    risk_score: 25,
    risk_category: "Low Risk",
    calculated_premium: 5750,
    claim_reserve: 15000,
  }
];
